# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 19 Kislev Archive
author: "Leonid Dubinsky"
email: dub@podval.org

description: >- # this means to ignore newlines until "baseurl:"
  Archive documents of the arrest of the Alter Rebbe and chassidim of
  Vilno in 1798 and the second arrest of 1800.

  Transcripts of the documents, identification of documents,
  suggestions etc. are welcome.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.alter-rebbe.org"

github_username:  dubinsky
# twitter_username: leoniddubinsky

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - README.md
  - people-and-places.md

# Build settings
markdown: kramdown
theme: minima

include:
  - README.md
  - people-and-places.md

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      math: false
