# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 19 Kislev Archive
author: "Leonid Dubinsky"
email: dub@podval.org

description: >- # this means to ignore newlines until "baseurl:"
  Archive documents of the arrests of the Alter
  Rebbe and chassidim of Vilno in 1798 and 1800.
  Transcripts and suggestions are welcome.
  Mailing list: alter-rebbe@podval.org

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alter-rebbe.org"
timezone: America/New_York

github_username:  dubinsky

theme: minima
markdown: kramdown

exclude:
  - buld.gradle
  - CNAME
  - Gemfile
  - Gemfile.lock

header_pages:
  - collections/rgada/index.html
  - collections/rgia413/index.html
  - collections/rgia2213/index.html
  - collections/dubnov/index.html
  - collections/lvia1/index.html
  - collections/lvia6/index.html
  - names.html
# header_pages end
  - blog.md