title: 'Документы'
author: "www.alter-rebbe.org"
email: dub@opentorah.org

description: >- # this means to ignore newlines until "baseurl:"
  documents related to early Chabad history
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://www.alter-rebbe.org"
timezone: America/New_York
google_analytics: UA-154490117-1

markdown: kramdown
theme: minima

header_pages:
  - names.html
  - collections.html
  - help.md
  - about.md

exclude:
  #  - store/collections/
  #  - collections/
  #  - store/names/
  #  - names/
  - CNAME
  - Gemfile
  - Gemfile.lock
