name: "CI"
on:
  push:
    branches:
      - 'master'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up Java"
        uses: actions/setup-java@master
        with:
          java-version: 11

      - name: "Generate and upload to Google Storage bucket"
        env:
          gcloudServiceAccountKey: ${{secrets.gcloudServiceAccountKey}}
        run: ./gradlew --no-daemon --console=plain uploadSite
